routes/web.php
<?php
Route::redirect('/', 'admin/home');

Auth::routes(['register' => false]);

Route::group(['middleware' => ['checkstatus']], function () {
    Route::post('/login', 'Auth\LoginController@login');
});

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/terms-and-conditions', 'HomeController@termsAndConditions')->name('termsAndConditions');
    Route::post('/terms-and-conditions', 'HomeController@saveTermsAndConditions')->name('saveTermsAndConditions');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::delete('permissions_mass_destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.mass_destroy');
    Route::resource('roles', 'Admin\RolesController');
    Route::delete('roles_mass_destroy', 'Admin\RolesController@massDestroy')->name('roles.mass_destroy');
    Route::resource('users', 'Admin\UsersController');
    Route::post('users/status/change', 'Admin\UsersController@changeStatus');
    Route::get('users/supplier/create', 'Admin\UsersController@createSupplier')->name('supplier.create');
    Route::get('users/supplier/{user}/edit', 'Admin\UsersController@editSupplier')->name('supplier.edit');
    Route::get('user/suppliers', 'Admin\UsersController@listSuppliers')->name('supplier.list');
    Route::get('user/supplier/view/{id}', 'Admin\SupplierController@supplierSingle')->name('supplier.single');
    Route::delete('users_mass_destroy', 'Admin\UsersController@massDestroy')->name('users.mass_destroy');

    Route::post('update/website', 'Admin\SupplierController@websiteUpdate')->name('update.website');
    Route::post('update/supplier', 'Admin\SupplierController@supplierUpdate')->name('update.supplier');

    //product
    Route::post('product/save', 'Admin\ProductController@productSave')->name('product.save');    
    Route::post('product/update', 'Admin\ProductController@productUpdate')->name('product.update');
    Route::post('product/single/get', 'Admin\ProductController@productSingle')->name('product.single.get');
    Route::post('product/single/stockcount/update', 'Admin\ProductController@productStockCountUpdate')->name('product.stockcount.update');
    // check product id
    Route::post('/check/product-id', 'Admin\ProductController@checkProductId')->name('product_id.check');
    //    CSV import
    Route::post('import/csv', 'Admin\ImportController@import')->name('csv.import');

    // activity log
    Route::get('activitylog/view', 'Admin\ActivityLogController@view')->name('activitylog.view');

    
    
    // settings
    Route::get('settings/general', 'Admin\SettingsController@index')->name('settings.general');
    Route::post('settings/general/save', 'Admin\SettingsController@save')->name('settings.general.save');

});

resources/views/home.blade.php
@extends('layouts.admin')

@section('content')
    <div class="content">
        <div class="row">
            <div class="col-lg-12">
                <h2>Dashboard</h2>
            </div>
        </div>
        {{--    admin dashboard--}}
        @can('admin_dashboard')
            <br>
            <div class="row">
                <div class="col-6 col-sm-4 col-md-3">
                    <a href="{{ route("admin.permissions.create") }}"
                       class="">
                        <div class="card mn200 ybox ">
                            <div class="media">
                                <p class="dashnumber">
                                    <ion-icon name="medkit-outline"></ion-icon>
                                </p>
                                <div class="media-body">
                                    <h5 class="dashhead">Add Permission</h5>

                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-6 col-sm-4 col-md-3">
                    <a href="{{ route("admin.permissions.index") }}"
                       class="">
                        <div class="card mn200 ybox ">
                            <div class="media">
                                <p class="dashnumber">
                                    <ion-icon name="list-outline"></ion-icon>
                                </p>
                                <div class="media-body">
                                    <h5 class="dashhead">List Permission</h5>

                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-6 col-sm-4 col-md-3">
                    <a href="{{ route("admin.roles.create") }}"
                       class="">
                        <div class="card mn200 ybox ">
                            <div class="media">
                                <p class="dashnumber">
                                    <ion-icon name="id-card-outline"></ion-icon>
                                </p>
                                <div class="media-body">
                                    <h5 class="dashhead">Add Roles</h5>

                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-6 col-sm-4 col-md-3">
                    <a href="{{ route("admin.roles.index") }}"
                       class="">
                        <div class="card mn200 ybox ">
                            <div class="media">
                                <p class="dashnumber">
                                    <ion-icon name="finger-print-outline"></ion-icon>
                                </p>
                                <div class="media-body">
                                    <h5 class="dashhead">List Roles</h5>

                                </div>
                            </div>
                        </div>
                    </a>
                </div>

            </div>
            <div class="row">
                <div class="col-6 col-sm-4 col-md-3">
                    <a href="{{ route("admin.users.create") }}"
                       class="">
                        <div class="card mn200 ybox ">
                            <div class="media">
                                <p class="dashnumber">
                                    <ion-icon name="person-add-outline"></ion-icon>
                                </p>
                                <div class="media-body">
                                    <h5 class="dashhead">Add User</h5>

                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-6 col-sm-4 col-md-3">
                    <a href="{{ route("admin.users.index") }}"
                       class="">
                        <div class="card mn200 ybox ">
                            <div class="media">
                                <p class="dashnumber">
                                    <ion-icon name="people-outline"></ion-icon>
                                </p>
                                <div class="media-body">
                                    <h5 class="dashhead">List Users</h5>

                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-6 col-sm-4 col-md-3">
                    <a href="/admin/users?type=Admin"
                       class="">
                        <div class="card mn200 ybox ">
                            <div class="media">
                                <p class="dashnumber">
                                    <ion-icon name="people-circle-outline"></ion-icon>
                                </p>
                                <div class="media-body">
                                    <h5 class="dashhead">List Admins</h5>

                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-6 col-sm-4 col-md-3">
                    <a href="{{ route("admin.supplier.list") }}"
                       class="">
                        <div class="card mn200 ybox ">
                            <div class="media">
                                <p class="dashnumber">
                                    <ion-icon name="storefront-outline"></ion-icon>
                                </p>
                                <div class="media-body">
                                    <h5 class="dashhead">List Suppliers</h5>

                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-6 col-sm-4 col-md-3">
                    <a href="{{ route("admin.supplier.create") }}"
                       class="">
                        <div class="card mn200 ybox ">
                            <div class="media">
                                <p class="dashnumber">
                                    <ion-icon name="people-outline"></ion-icon>
                                </p>
                                <div class="media-body">
                                    <h5 class="dashhead">Add Supplier</h5>

                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                
            </div>


        @endcan
        {{--   END admin dashboard--}}

        {{--  manager dashboard--}}
        @can('manager_dashboard')

            <div class="col-6 col-sm-4 col-md-3">
                <a href="{{ route("admin.supplier.create") }}"
                   class="">
                    <div class="card mn200 ybox ">
                        <div class="media">
                            <p class="dashnumber">
                                <ion-icon name="people-outline"></ion-icon>
                            </p>
                            <div class="media-body">
                                <h5 class="dashhead">Add Supplier</h5>

                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-6 col-sm-4 col-md-3">
                <a href="{{ route("admin.supplier.list") }}"
                   class="">
                    <div class="card mn200 ybox ">
                        <div class="media">
                            <p class="dashnumber">
                                <ion-icon name="storefront-outline"></ion-icon>
                            </p>
                            <div class="media-body">
                                <h5 class="dashhead">List Suppliers</h5>

                            </div>
                        </div>
                    </div>
                </a>
            </div>
        @endcan
        {{--   END manager dashboard--}}
        
        {{--    supplier dashboard--}}
        @can('supplier_dashboard')
            <br>
            <div class="row">
                <div class="col-6 col-sm-4 col-md-3">
                    <a href="{{route('admin.supplier.single',['id'=>\Illuminate\Support\Facades\Auth::user()->id])}}"
                       class="">
                        <div class="card mn200 ybox ">
                            <div class="media">
                                <p class="dashnumber">
                                    <ion-icon name="storefront-outline"></ion-icon>
                                </p>
                                <div class="media-body">
                                    <h5 class="dashhead">Data Population</h5>

                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        @endcan
        {{--   END supplier dashboard--}}

         {{--    supplier dashboard--}}
         @can('data_entry_dashboard')
         <br>
         <div class="row">
            <div class="col-6 col-sm-4 col-md-3">
                <a href="{{ route("admin.supplier.list") }}"
                   class="">
                    <div class="card mn200 ybox ">
                        <div class="media">
                            <p class="dashnumber">
                                <ion-icon name="storefront-outline"></ion-icon>
                            </p>
                            <div class="media-body">
                                <h5 class="dashhead">List Suppliers</h5>

                            </div>
                        </div>
                    </div>
                </a>
            </div>
         </div>
     @endcan
     {{--   END supplier dashboard--}}


    </div>
@endsection
@section('scripts')
    @parent

@endsection

resources/views/tc.blade.php
@extends('layouts.plain')

@section('content')
    <div class="container" style="margin-top: 30px;">
        <div class="row">
            <div class="col-lg-12">
                <h2>Terms And Conditions</h2>
            </div>
            <div class="col-lg-12">
                <div style="    max-height: 550px;
                overflow-y: scroll;
                background:#fff;
                padding:20px;
                border-radius:10px">
                    <p>
                        What is Lorem Ipsum?
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

Why do we use it?
It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).


Where does it come from?
Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.

Where can I get some?
There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.
                    </p>
                    <p>
                        What is Lorem Ipsum?
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

Why do we use it?
It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).


Where does it come from?
Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.

Where can I get some?
There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.
                    </p>
                </div>
            </div>
            <div class="col-lg-12" style="margin-top: 20px;">
                <form action="{{route('admin.saveTermsAndConditions')}}" method="post">
                    {{ csrf_field() }}
                    <input type="hidden" value="{{$user->id}}" name="user_id">
                    <input type="hidden" value="1" name="agree">
                    <button type="submit" class="btn btn-success btn-lg float-right" style="font-size: 18px;
                    padding: 10px 20px;
                    border-radius: 5px;">I Agree</button>
                </form>

            </div>
        </div>



    </div>
@endsection
@section('scripts')
    @parent

@endsection