routes/web.php
<?php
Route::redirect('/', 'admin/home');

Auth::routes(['register' => false]);

Route::group(['middleware' => ['checkstatus']], function () {
    Route::post('/login', 'Auth\LoginController@login');
});

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/terms-and-conditions', 'HomeController@termsAndConditions')->name('termsAndConditions');
    Route::post('/terms-and-conditions', 'HomeController@saveTermsAndConditions')->name('saveTermsAndConditions');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::delete('permissions_mass_destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.mass_destroy');
    Route::resource('roles', 'Admin\RolesController');
    Route::delete('roles_mass_destroy', 'Admin\RolesController@massDestroy')->name('roles.mass_destroy');
    Route::resource('users', 'Admin\UsersController');
    Route::post('users/status/change', 'Admin\UsersController@changeStatus');
    Route::get('users/supplier/create', 'Admin\UsersController@createSupplier')->name('supplier.create');
    Route::get('users/supplier/{user}/edit', 'Admin\UsersController@editSupplier')->name('supplier.edit');
    Route::get('user/suppliers', 'Admin\UsersController@listSuppliers')->name('supplier.list');
    Route::get('user/supplier/view/{id}', 'Admin\SupplierController@supplierSingle')->name('supplier.single');
    Route::delete('users_mass_destroy', 'Admin\UsersController@massDestroy')->name('users.mass_destroy');

    Route::post('update/website', 'Admin\SupplierController@websiteUpdate')->name('update.website');
    Route::post('update/supplier', 'Admin\SupplierController@supplierUpdate')->name('update.supplier');

    //product
    Route::post('product/save', 'Admin\ProductController@productSave')->name('product.save');    
    Route::post('product/update', 'Admin\ProductController@productUpdate')->name('product.update');
    Route::post('product/single/get', 'Admin\ProductController@productSingle')->name('product.single.get');
    Route::post('product/single/stockcount/update', 'Admin\ProductController@productStockCountUpdate')->name('product.stockcount.update');
    // check product id
    Route::post('/check/product-id', 'Admin\ProductController@checkProductId')->name('product_id.check');
    //    CSV import
    Route::post('import/csv', 'Admin\ImportController@import')->name('csv.import');

    // activity log
    Route::get('activitylog/view', 'Admin\ActivityLogController@view')->name('activitylog.view');

    
    
    // settings
    Route::get('settings/general', 'Admin\SettingsController@index')->name('settings.general');
    Route::post('settings/general/save', 'Admin\SettingsController@save')->name('settings.general.save');

});

app/User.php
<?php
namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
use Hash;

/**
 * Class User
 *
 * @package App
 * @property string $name
 * @property string $email
 * @property string $password
 * @property string $remember_token
*/
class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;

    protected $fillable = ['name', 'email', 'password', 'remember_token','supplier_code','is_changed','t_c_acknowledged'];
    
    
    /**
     * Hash password
     * @param $input
     */
    public function setPasswordAttribute($input)
    {
        if ($input)
            $this->attributes['password'] = app('hash')->needsRehash($input) ? Hash::make($input) : $input;
    }
    
    
    public function role()
    {
        return $this->belongsToMany(Role::class, 'role_user');
    }
    
    
    
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Spatie\Permission\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreUsersRequest;
use App\Http\Requests\Admin\UpdateUsersRequest;
use Illuminate\Support\Facades\Auth;

class UsersController extends Controller
{
    /**
     * Display a listing of User.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (!$this->checkAuth()) {
            return abort(401);
        }

        $users = User::all();

        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating new User.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (!$this->checkAuth()) {
            return abort(401);
        }
        $roles = Role::get()->pluck('name', 'name');

        return view('admin.users.create', compact('roles'));
    }

    /**
     * Show the form for creating new User.
     *
     * @return \Illuminate\Http\Response
     */
    public function createSupplier()
    {
        if (!$this->checkAuth()) {
            return abort(401);
        }
        $roles = Role::get()->pluck('name', 'name');

        return view('admin.users.create_supplier', compact('roles'));
    }

    /**
     * Store a newly created User in storage.
     *
     * @param  \App\Http\Requests\StoreUsersRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUsersRequest $request)
    {
        if (!$this->checkAuth()) {
            return abort(401);
        }
        if ($request->supplier_code){
            $res = User::where('supplier_code',$request->supplier_code)->count();
            if ($res > 0){
                session()->flash('error', 'Supplier code "'.$request->supplier_code.'"already exists!');
                return redirect()->back();
            }
        }
        $user = User::create($request->all());

        $roles = $request->input('roles') ? $request->input('roles') : [];
        $user->assignRole($roles);

        if (isset($request->supplier_code) or in_array('supplier', $roles)) {
            $user->supplier_code = isset($request->supplier_code) ? $request->supplier_code : $this->generateSupplierCode($user);
            $user->save();
        }
        app(ActivityLogController::class)->CreateLogRecord(Auth::user()->id, 'create_user');
        return redirect()->route('admin.users.index');
    }


    /**
     * Show the form for editing User.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        if (!$this->checkAuth()) {
            return abort(401);
        }
        $roles = Role::get()->pluck('name', 'name');

        return view('admin.users.edit', compact('user', 'roles'));
    }

    /**
     * Show the form for editing User.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function editSupplier(User $user)
    {
        if (!$this->checkAuth()) {
            return abort(401);
        }
        $roles = Role::get()->pluck('name', 'name');

        return view('admin.users.edit_supplier', compact('user', 'roles'));
    }

    /**
     * Update User in storage.
     *
     * @param  \App\Http\Requests\UpdateUsersRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUsersRequest $request, User $user)
    {
        if (!$this->checkAuth()) {
            return abort(401);
        }
        if ($request->supplier_code){
            $res = User::where('supplier_code',$request->supplier_code)->where('id','!=',$user->id)->count();
            if ($res > 0){
                session()->flash('error', 'Supplier code "'.$request->supplier_code.'"already exists!');
               return redirect()->back();
            }
        }

        $user->update($request->all());
        $roles = $request->input('roles') ? $request->input('roles') : [];
        $user->syncRoles($roles);
        app(ActivityLogController::class)->CreateLogRecord(Auth::user()->id, 'update_user');
        return redirect()->route('admin.users.index');
    }

    public function show(User $user)
    {
        if (!$this->checkAuth()) {
            return abort(401);
        }

        $user->load('roles');

        return view('admin.users.show', compact('user'));
    }

    /**
     * Remove User from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        if (!$this->checkAuth()) {
            return abort(401);
        }

        $user->delete();
        app(ActivityLogController::class)->CreateLogRecord(Auth::user()->id, 'delete_user');
        return redirect()->route('admin.users.index');
    }

    /**
     * Delete all selected User at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (!$this->checkAuth()) {
            return abort(401);
        }
        User::whereIn('id', request('ids'))->delete();
        app(ActivityLogController::class)->CreateLogRecord(Auth::user()->id, 'mass_delete_user');
        return response()->noContent();
    }

    /**
     * Display a listing of User.
     *
     * @return \Illuminate\Http\Response
     */
    public function listSuppliers()
    {
        if (!$this->checkAuth()) {
            return abort(401);
        }
        $supplier_code = request()->supplier_code;

        if(!empty($supplier_code)){
            $users = User::where('supplier_code',$supplier_code)
            ->orWhere('name', 'like', '%'.$supplier_code.'%')->get();
        }else{
            $users = User::all();
        }

        return view('admin.users.suppiers', compact('users'));
    }

    public function checkAuth()
    {
        if (Gate::allows('users_manage')) {
            return true;
        } elseif (Gate::allows('user_add')) {
            return true;
        } elseif (Gate::allows('list_suppliers')) {
            return true;
        } else {
            return false;
        }
    }

    public function generateSupplierCode($user)
    {
        if (!empty($user->name)) {
            $name = strtoupper(substr(str_replace(' ', '', $user->name), 0, 2));
            $num = $invID = str_pad($user->id, 4, '0', STR_PAD_LEFT);
            return $name . $num;
        }
    }

    public function changeStatus(Request $request)
    {
        if (!$this->checkAuth()) {
            return abort(401);
        }

        if ($request->status == 'deactivate') {
            return User::where('id',$request->id)->update(['status'=>0]);
        }else{
            return User::where('id',$request->id)->update(['status'=>1]);
        }
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="row">
    
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                {{ trans('global.create') }} {{ trans('cruds.user.title_singular') }}
            </div>
        
            <div class="card-body">
                <form action="{{ route("admin.users.store") }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                        <label for="name">{{ trans('cruds.user.fields.name') }}*</label>
                        <input type="text" id="name" name="name" class="form-control" value="{{ old('name', isset($user) ? $user->name : '') }}" required>
                        @if($errors->has('name'))
                            <em class="invalid-feedback">
                                {{ $errors->first('name') }}
                            </em>
                        @endif
                        <p class="helper-block">
                            {{ trans('cruds.user.fields.name_helper') }}
                        </p>
                    </div>
                    <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                        <label for="email">{{ trans('cruds.user.fields.email') }}*</label>
                        <input type="email" id="email" name="email" class="form-control" value="{{ old('email', isset($user) ? $user->email : '') }}" required>
                        @if($errors->has('email'))
                            <em class="invalid-feedback">
                                {{ $errors->first('email') }}
                            </em>
                        @endif
                        <p class="helper-block">
                            {{ trans('cruds.user.fields.email_helper') }}
                        </p>
                    </div>
                    <div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                        <label for="password">{{ trans('cruds.user.fields.password') }}</label>
                        <input type="password" id="password" name="password" class="form-control" required>
                        @if($errors->has('password'))
                            <em class="invalid-feedback">
                                {{ $errors->first('password') }}
                            </em>
                        @endif
                        <p class="helper-block">
                            {{ trans('cruds.user.fields.password_helper') }}
                        </p>
                    </div>
                    <div class="form-group {{ $errors->has('roles') ? 'has-error' : '' }}">
                        <label for="roles">{{ trans('cruds.user.fields.roles') }}*
        
                        @if (request()->input('role') != null AND request()->input('role') == 'manager')
                            <select name="roles[]" id="roles" class="form-control" required disabled>
                                @foreach($roles as $id => $roles)
                                    <option value="{{ $id }}" {{ $roles == 'supplier' ? 'selected' : '' }}>{{ $roles }}</option>
                                @endforeach
                            </select>
                        @else
                                <span class="btn btn-info btn-xs select-all">{{ trans('global.select_all') }}</span>
                                <span class="btn btn-info btn-xs deselect-all">{{ trans('global.deselect_all') }}</span></label>
                            <select name="roles[]" id="roles" class="form-control select2" multiple="multiple" required>
                                @foreach($roles as $id => $roles)
                                    <option value="{{ $id }}" {{ (in_array($id, old('roles', [])) || isset($user) && $user->roles->contains($id)) ? 'selected' : '' }}>{{ $roles }}</option>
                                @endforeach
                            </select>
                        @endif
        
                        @if($errors->has('roles'))
                            <em class="invalid-feedback">
                                {{ $errors->first('roles') }}
                            </em>
                        @endif
                        <p class="helper-block">
                            {{ trans('cruds.user.fields.roles_helper') }}
                        </p>
                    </div>
                    <div>
                        <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
                    </div>
                </form>
        
        
            </div>
        </div>
    </div>
    <div class="col-md-4">
        @include('admin.users.password_gen')
    </div>
</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.admin')
@section('content')
    @can('users_manage')
        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                @if (request()->input('type') == null)
                    <a class="btn btn-success addbtn" href="{{ route("admin.users.create") }}">
                        {{ trans('global.add') }} {{ trans('cruds.user.title_singular') }}
                    </a>
                @endif
            </div>
        </div>
    @endcan
    <div class="card">
        <div class="card-header">
            {{ trans('cruds.user.title_singular') }} {{ trans('global.list') }}
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class=" table table-bordered table-striped table-hover datatable datatable-User">
                    <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.user.fields.id') }}
                        </th>
                        <th>
                            Code
                        </th>
                        <th>
                            {{ trans('cruds.user.fields.name') }}
                        </th>
                        <th>
                            {{ trans('cruds.user.fields.email') }}
                        </th>
                        <th>
                            {{ trans('cruds.user.fields.roles') }}
                        </th>
                        <th width="2%">
                            Status
                        </th>
                        <th width="2%">
                            &nbsp;
                        </th>
                        <th width="2%">
                            &nbsp;
                        </th>
                        <th width="2%">
                            &nbsp;
                        </th>
                        <th width="2%">
                            &nbsp;
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $key => $user)
                        @php
                            if (request()->input('type') != null){
                                $visible = in_array(request()->input('type'), $user->roles()->pluck('name')->toArray());
                            }else{
                                $visible = true;
                            }
                        @endphp
                        @if($visible == true)
                            <tr data-entry-id="{{ $user->id }}">
                                <td>

                                </td>
                                <td>
                                    {{ $user->id ?? '' }}
                                </td>
                                <td>
                                    {{ $user->supplier_code ?? '-' }}
                                </td>
                                <td>
                                    {{ $user->name ?? '' }}
                                </td>
                                <td>
                                    {{ $user->email ?? '' }}
                                </td>
                                <td>
                                    @foreach($user->roles()->pluck('name') as $role)
                                        <span class="badge badge-info">{{ $role }}</span>
                                    @endforeach
                                </td>
                                <td>
                                    @if($user->status)
                                        <span class="badge badge-success">Active</span>
                                    @else
                                        <span class="badge badge-danger">Deactive</span>
                                    @endif
                                </td>
                                <td>
                                    @if($user->status)
                                        <button class="btn btn-xs btn-danger"
                                                onclick="changeStatus({{$user->id}}, 'deactivate')">
                                            Deactivate
                                        </button>
                                    @else
                                        <button class="btn btn-xs btn-success"
                                                onclick="changeStatus({{$user->id}}, 'activate')">
                                            Activate
                                        </button>
                                    @endif

                                </td>
                                <td>
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.users.show', $user->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                </td>
                                <td>
                                    @if(empty($user->supplier_code))
                                        <a class="btn btn-xs btn-info"
                                           href="{{ route('admin.users.edit', $user->id) }}">
                                            {{ trans('global.edit') }}
                                        </a>
                                    @else
                                        <a class="btn btn-xs btn-info"
                                           href="{{route('admin.supplier.edit',$user->id)}}">
                                            {{ trans('global.edit') }}
                                        </a>
                                    @endif
                                </td>
                                <td>
                                    <form action="{{ route('admin.users.destroy', $user->id) }}" method="POST"
                                          onsubmit="return confirm('{{ trans('global.areYouSure') }}');"
                                          style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger"
                                               value="{{ trans('global.delete') }}">
                                    </form>

                                </td>

                            </tr>
                        @endif
                    @endforeach
                    </tbody>
                </table>
            </div>


        </div>
    </div>
@endsection
@section('scripts')
    @parent
    <script>
        $(function () {
            let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
                    @can('users_manage')
            let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
            let deleteButton = {
                text: deleteButtonTrans,
                url: "{{ route('admin.users.mass_destroy') }}",
                className: 'btn-danger',
                action: function (e, dt, node, config) {
                    var ids = $.map(dt.rows({selected: true}).nodes(), function (entry) {
                        return $(entry).data('entry-id')
                    });

                    if (ids.length === 0) {
                        alert('{{ trans('global.datatables.zero_selected') }}')

                        return
                    }

                    if (confirm('{{ trans('global.areYouSure') }}')) {
                        $.ajax({
                            headers: {'x-csrf-token': _token},
                            method: 'POST',
                            url: config.url,
                            data: {ids: ids, _method: 'DELETE'}
                        })
                            .done(function () {
                                location.reload()
                            })
                    }
                }
            }
            dtButtons.push(deleteButton)
            @endcan

            $.extend(true, $.fn.dataTable.defaults, {
                order: [[1, 'asc']],
                pageLength: 100,
            });
            $('.datatable-User:not(.ajaxTable)').DataTable({buttons: dtButtons})
            $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
                $($.fn.dataTable.tables(true)).DataTable()
                    .columns.adjust();
            });
        });


        function changeStatus(id, status) {
            Swal.fire({
                title: 'Do you wish ' + status + ' this user?',
                text: '',
                showCancelButton: true,
                confirmButtonText: 'Yes',
                cancelButtonText: 'No'
            }).then((result) = > {
                /* Read more about isConfirmed, isDenied below */
                if(result.isConfirmed
        )
            {
                $.ajax({
                    headers: {'x-csrf-token': _token},
                    method: 'POST',
                    url: '/admin/users/status/change',
                    data: {id: id, status: status}
                })
                    .done(function (res) {
                        console.log(res);
                        if (res) {
                            var msg = 'User ' + status + ' successfully!';
                            $('#js_msg').html('<div class="alert alert-success" role="alert">' + msg + '</div>');

                            setTimeout(function (e) {
                                location.reload();
                            }, 1500);
                        }
                    })
            }
        })
            ;
        }


    </script>
@endsection

resources/views/admin/users/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.user.title') }}
    </div>

    <div class="card-body">
        <div class="mb-2">
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.user.fields.id') }}
                        </th>
                        <td>
                            {{ $user->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.user.fields.name') }}
                        </th>
                        <td>
                            {{ $user->name }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.user.fields.email') }}
                        </th>
                        <td>
                            {{ $user->email }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Roles
                        </th>
                        <td>
                            @foreach($user->roles()->pluck('name') as $role)
                                <span class="label label-info label-many">{{ $role }}</span>
                            @endforeach
                        </td>
                    </tr>
                </tbody>
            </table>
            <a style="margin-top:20px;" class="btn btn-default" href="{{ url()->previous() }}">
                {{ trans('global.back_to_list') }}
            </a>
        </div>


    </div>
</div>
@endsection

resources/views/admin/users/suppiers.blade.php
@extends('layouts.admin')
@section('content')
    <div class="card">
        <div class="card-header">
            {{ trans('cruds.supplier.title_singular') }} {{ trans('global.list') }}
            <div class="pull-right">
                <form action="" method="GET">
                    <div class="input-group">
                        <input type="text" class="form-control" id="" placeholder="Search Suppler here" name="supplier_code" required>
                        <div class="input-group-append">
                            <button class="btn btn-sm btn-secondary" style="border-radius: 0px 5px 5px 0px;" type="submit">
                                <i class="fas fa-fw fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="card-body">
            <div class="row">

            @foreach($users as $key => $user)
                @php
                    $visible = in_array('supplier', $user->roles()->pluck('name')->toArray());
                @endphp
                @if($visible == true)
                        <div class="col-3 col-sm-3 col-md-3 mb-3 mb-xl-0">
                            <a href="{{route('admin.supplier.single',['id'=>$user->id])}}"
                               class="btn btn-block btn-lg mt-2 {{$user->is_changed ? 'btn-danger' : 'btn-warning'}}"
                               type="button">{{($user->supplier_code) ? $user->supplier_code : $user->name}}</a>
                        </div>
                @endif
            @endforeach
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    @parent
    <script>
        $(function () {
            let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
            @can('users_manage')
            let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
            let deleteButton = {
                text: deleteButtonTrans,
                url: "{{ route('admin.users.mass_destroy') }}",
                className: 'btn-danger',
                action: function (e, dt, node, config) {
                    var ids = $.map(dt.rows({selected: true}).nodes(), function (entry) {
                        return $(entry).data('entry-id')
                    });

                    if (ids.length === 0) {
                        alert('{{ trans('global.datatables.zero_selected') }}')

                        return
                    }

                    if (confirm('{{ trans('global.areYouSure') }}')) {
                        $.ajax({
                            headers: {'x-csrf-token': _token},
                            method: 'POST',
                            url: config.url,
                            data: {ids: ids, _method: 'DELETE'}
                        })
                            .done(function () {
                                location.reload()
                            })
                    }
                }
            }
            dtButtons.push(deleteButton)
            @endcan

            $.extend(true, $.fn.dataTable.defaults, {
                order: [[1, 'desc']],
                pageLength: 100,
            });
            $('.datatable-User:not(.ajaxTable)').DataTable({buttons: dtButtons})
            $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
                $($.fn.dataTable.tables(true)).DataTable()
                    .columns.adjust();
            });
        })

    </script>
@endsection